# Generated by Django 5.2.1 on 2025-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='added_at',
            field=models.DateTimeField(default='2025-05-30 13:52:00+03:00', verbose_name='Дата добавления', auto_now_add=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='added_at',
            field=models.DateTimeField(default='2025-05-30 13:52:00+03:00', verbose_name='Дата добавления', auto_now_add=True),
        ),
    ]
